## Packages----
suppressPackageStartupMessages({
    library(readr)
    library(readODS)
    library(readxl)
    library(forecast)
    library(haven)
    library(gnm)
    library(logmult)
    library(lme4)
    library(Rfast)
    library(lmtest)
    library(survey)
    library(sjPlot)
    library(ggeffects)
    library(margins)
    library(expss)
    library(plm)
    library(lattice)
    library(svglite)
    library(stringr)
    library(scales)
    library(dplyr)
    library(tidyverse)
    library(tidylog)
    library(janitor)
    library(haven)
    library(labelled)
    library(here)
    library(sf)
    library(ggplot2)
    library(tmap)
    library(ggpubr)
    library(cowplot)
    library(magick) #convert png to svg
    library(sjlabelled) #to extract row labels
})